
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 07 20:15:43 CST 2024
//----------------------------------------------------

package demo_cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 30;
  public static final int SIGNED = 36;
  public static final int BOOL = 24;
  public static final int TYPEID = 33;
  public static final int COMENTARIOU = 65;
  public static final int COUT = 59;
  public static final int OPERADOR_MAIQ = 70;
  public static final int COMENTARIOM = 66;
  public static final int CONST = 60;
  public static final int PARENTESIS_CIERRE = 7;
  public static final int DIVI = 74;
  public static final int REGISTER = 51;
  public static final int NAMESPACE = 54;
  public static final int CORCHETE_APERTURA = 8;
  public static final int SIZEOF = 37;
  public static final int VIRTUAL = 46;
  public static final int THROW = 27;
  public static final int LLAVE_APER = 76;
  public static final int DOUBLE = 35;
  public static final int STRUCT = 39;
  public static final int PROTECTED = 55;
  public static final int FALSE = 23;
  public static final int NOT = 13;
  public static final int MULTI = 73;
  public static final int ERROR = 2;
  public static final int FLOAT = 17;
  public static final int DOS_PUNTOS = 5;
  public static final int PACKAGE = 47;
  public static final int OPERADOR_RELACIONAL = 10;
  public static final int PUNTO_COMA = 63;
  public static final int CLASS = 32;
  public static final int COMA = 4;
  public static final int ENTERO = 81;
  public static final int TRUE = 22;
  public static final int LONG = 78;
  public static final int WHILE = 31;
  public static final int UNION = 28;
  public static final int LLAVE_CERR = 77;
  public static final int CHAR = 25;
  public static final int SWITCH = 40;
  public static final int DO = 15;
  public static final int FOR = 58;
  public static final int VOID = 26;
  public static final int PUBLIC = 41;
  public static final int RETURN = 34;
  public static final int OPERADOR_MAQ = 68;
  public static final int ELSE = 57;
  public static final int TRY = 20;
  public static final int INT = 16;
  public static final int EOF = 0;
  public static final int PUNTO = 3;
  public static final int THIS = 21;
  public static final int MUTABLE = 44;
  public static final int OPERATOR = 50;
  public static final int CONSTANTE = 61;
  public static final int CARACTER = 79;
  public static final int IMPORT = 42;
  public static final int OR = 12;
  public static final int error = 1;
  public static final int RESTA = 72;
  public static final int IF = 56;
  public static final int UNSIGNED = 52;
  public static final int ID = 80;
  public static final int PARENTESIS_APERTURA = 6;
  public static final int TEMPLATE = 48;
  public static final int USING = 29;
  public static final int OPERADOR_ARITMETICO = 64;
  public static final int FLOTANTE = 75;
  public static final int VOLATILE = 53;
  public static final int OPERADOR_D = 71;
  public static final int ASIGNACION = 62;
  public static final int CADENA = 14;
  public static final int NEW = 19;
  public static final int TYPENAME = 49;
  public static final int STRING = 18;
  public static final int OPERADOR_MEQ = 67;
  public static final int AND = 11;
  public static final int OPERADOR_MEIQ = 69;
  public static final int CORCHETE_CIERRE = 9;
  public static final int PRIVATE = 45;
  public static final int STATIC = 38;
  public static final int TYPEDEF = 43;
}

